# Generated by Django 5.0.2 on 2024-06-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
